{% set name = "rapid-pe" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapid_pe-{{ version }}.tar.gz
  sha256: 17dd8ab0a0419e8d455f79eb4f4cde9a110085ca50f6d4ea7c50a416a44d3da2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - h5py
    - lalsuite
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - python
    - scikit-learn
    - scipy
    - six

test:
  imports:
    - rapid_pe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/rapidpe-rift/rapidpe/
  summary: 'RapidPE: The original low-latency gravitational wave parameter estimation code.'
  license: GPL-2.0-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - dwysocki
