{% set name = "rapid-pe" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapid_pe-{{ version }}.tar.gz
  sha256: 4f252725aa179ddffeba31e108ef9f9a6ce8a76c2fad916d6c1bc2c8e961ac4c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - h5py
    - lalsuite
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - python
    - scikit-learn
    - scipy
    - six

test:
  imports:
    - rapid_pe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/rapidpe-rift/rapidpe/
  summary: 'RapidPE: The original low-latency gravitational wave parameter estimation code.'
  license: GPL-2.0-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - dwysocki
