{% set name = "rapid-pe" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapid_pe-{{ version }}.tar.gz
  sha256: c269fe191579e128a11824af65948c22deac02addd8b8ea9e769856d73574b6b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - bilby
    - h5py
    - healpy
    - lalsuite
    - ligo.skymap
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - python
    - python-ligo-lw
    - scikit-learn
    - scipy
    - six

test:
  imports:
    - rapid_pe
  commands:
    - pip check
  requires:
    - pip
    # HACK: Something is wrong with pytables, which we don't even use but a
    #       dependency does, so I'm pinning this to an older version
    - pytables ==3.7.0

about:
  home: https://git.ligo.org/rapidpe-rift/rapidpe/
  summary: 'RapidPE: The original low-latency gravitational wave parameter estimation code.'
  license: GPL-2.0-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - dwysocki
    - vinaya-valsan
